### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by KaushikMalapati**
## Description

Once a new common-components is released, I will update the version here
Copied changes from FB_PPM_PowerMeter from cc to IM4K2
Fixed the responsivity value for IM6K2 (it was negative before but was not supposed to be)

## Motivation and Context

Noticed the negative responsivity on Saturday resulting in negative wattage calculated during beamtime
CC library update and changes to IM4K2 based on changes to common-components after the same Saturday test
https://github.com/pcdshub/lcls-twincat-common-components/pull/77
https://jira.slac.stanford.edu/browse/ECS-875

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

### CODE REVIEW

**Review by ZLLentz — COMMENTED** [review]
The update to the special class here matches the approved update to the library
Everything looks good
I think we can merge this no problem with a new common component library bugfix tag

**Comment by KaushikMalapati** [comment]
To summarize the changes

- Rebuilding ioc
- Updating common-components version to 3.8.4
- Removing negative sign on IM6K2 responsivity (confirmed with Philip this is correct now)
- Updating FB_PPM_PowerMeter_IM4K2 to match FB_PPM_Powermeter from latest common-components
- Making PF1K2 encoder minimum position -94.0 instead of -99.3299
- Changing IM1K1 fVelocity from 1 to 10
- Changing PF1K2 fTarget1 fPosition to -94.0

The last three changes are unrelated to the power meter code I have been working on, just putting them so they can be released.

**Review by ZLLentz — APPROVED** [review]
I think this looks good!

**Comment by KaushikMalapati** [comment]
@jyotiphy, can you please review the changes to IM1K1 and PF1K2 that you asked me to make? I will merge/release if they look alright.

**Pull request merged**
