### PR TITLE
RIX Motion PLC updates after adding new common components 

### PR DESCRIPTION
**Pull request by jyotiphy**
Commented out the axes which are not setup yet

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
I'm going to check the IOC build before merging just in case

**Comment by ZLLentz** [comment]
IOC build still fails, I think you need to rebuild/commit/push

**Comment by ZLLentz** [comment]
It's also possible that the IOC will be break with a numeric gap, e.g. motor Ids 17-22 are missing. I can't remember if we fixed that bug or not.

**Comment by jyotiphy** [comment]
I have removed the axes which are not setup from "NC" and also commented out M17-M26 in "Main". I believe that this should fix the IOC build issue. Can you please give it a try ?

**Comment by ZLLentz** [comment]
it built correctly now, do you want to deploy this or do you want to try with M23+?

**Pull request merged**
